name: Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main or develop branches
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.1
        
      - name: clean install dependencies
        run: npm ci
      
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9
        with:
            versionSpec: '5.1.x'

      - name: Execute GitVersion
        id: gitversion # step id used as reference for output values
        uses: gittools/actions/gitversion/execute@v0.9
        
      - name: Print version information
        run: |
          echo "Major: ${{ steps.gitversion.outputs.major }}"
          echo "Minor: ${{ steps.gitversion.outputs.minor }}"
          echo "Patch: ${{ steps.gitversion.outputs.patch }}"
          echo "MajorMinorPatch: ${{ steps.gitversion.outputs.majorMinorPatch }}"
          echo "SemVer: ${{ steps.gitversion.outputs.semVer }}"

      - name: Update metadata in package.json
        uses: onlyutkarsh/patch-files-action@v1.0.1
        with:
          files: '${{github.workspace}}/package.json'
          patch-syntax: |
            = /version => "${{ steps.gitversion.outputs.semVer }}"
      
      - name: Compile and create .vsix
        run: npm run package
        
      - name: Print vsix path
        run: |
          echo "VSIX Path: ${{ env.vsix_path }}"

      - name: Upload .vsix as artifact
        uses: actions/upload-artifact@v1
        with:
          name: yarn-spinner-${{steps.gitversion.outputs.semVer}}.vsix
          path: ${{github.workspace}}/yarn-spinner-${{steps.gitversion.outputs.semVer}}.vsix

        
